# specific configuration options for production environment
# that overrides the default ones
production:
  delivery_method: :sendmail

# specific configuration options for development environment
# that overrides the default ones
development:
  delivery_method: :sendmail
